src/Components/AnimalCard.js
src/Components/AnimalListView/AnimalFilter.js
src/Components/AnimalListView/AnimalList.js
src/Components/AnimalListView/index.js
src/Components/App.js
src/Components/index.js

This implements the AnimalListView as a collection of subcomponents which are implemented as colored divs.  These subcomponents are the AnimalFilter (to filter the animals shown in the AnimalList), the AnimalList (which shows AnimalCards), and the AnimalCard.  I used dummy data hard coded into the AnimalList component as the array of animals.  
I did not include a nav component.  I imagine that this would be part of the surrounding page, not the AnimalListView itself.  A nav bar could certainly be added if we decide that it should be part of the AnimalListView.

05 animal list display

---

src/Reducers/AnimalsReducer.js
src/Reducers/HostsReducer.js
src/Reducers/SheltersReducer.js
src/Reducers/index.js
src/dummyData.js

Reverts jayaimzzz/RescueForce#17

Revert "dummy data is in state in the redux store"

---

src/Reducers/AnimalsReducer.js
src/Reducers/HostsReducer.js
src/Reducers/SheltersReducer.js
src/Reducers/index.js
src/dummyData.js

Reverts jayaimzzz/RescueForce#18

Revert "Revert "dummy data is in state in the redux store""

---

src/Components/AnimalCard.js
src/Components/AnimalListView/AnimalList.js
src/Components/AnimalListView/index.js
src/dummyData.js

dummy data that is in state is being passed down to the animalcard component from the animallist

Animal List is connected to redux state.  Props are passed to card. 

---

src/Components/AnimalProfileView/AnimalProfile.js
src/Components/AnimalProfileView/ImageScroll.js
src/Components/AnimalProfileView/index.js
src/Components/HostListView/HostCard.js
src/Components/HostListView/HostFilter.js
src/Components/HostListView/index.js

This fills in the scaffolding for the AnimalProfileView and HostListView.

39 scaffold components

---

src/Components/AnimalList/AnimalCard.js
src/Components/AnimalListView/AnimalFilter.js
src/Components/AnimalProfileView/AnimalProfile.js
src/Components/AnimalProfileView/index.js
src/Components/FosterFamilyProfile.js
src/dummyData.js

This is a very very basic animal profile card that pulls the animal's information from state.  The card will be updated to include the modal window (through which an authorized user will be able to change state).  Submitting this request primarily for demo on Fri.

very basic animal profile for animal profile page

---

src/Components/DevNav/index.js

The places the dev nav below the fledgling real nav

added DevNav top margin

---

src/Components/AnimalProfileView/AnimalProfile.js
src/Components/HostListView/AnimalImgScroll.js
src/Components/HostProfileView/HostProfile.js

The API has been changed to populate hostId and shelterId with the host and shelter.  These changes keep everything working.

Populate hosts and shelter

---

src/ActionCreators/authActionCreator.js
src/Components/AnimalList/index.js
src/Components/HostProfileView/HostProfile.js
src/Components/HostProfileView/HostVacancies.js
src/Components/HostProfileView/index.js
src/Components/index.js

After a host logs in, they are redirected to their own profile page. When a logged in host view their own profile they also see a Edit Profile button, a welcome message at the top, and a list of animals available for fostering

74 host homepage2

---

src/ActionCreators/index.js
src/ActionCreators/shelterActionCreators.js
src/Components/App.js
src/Components/HostListView/HostCard.js
src/Components/HostProfileView/HostProfile.js
src/Components/HostProfileView/HostVacancies.js
src/Components/HostProfileView/index.js
src/Reducers/SheltersReducer.js

Added 'approved new host' button to a host's profile page when viewed by a shelter.  This button does nothing yet.  I will work on adding functionality once the updateHost action creator is complete.

94 approve new host

---

src/ActionCreators/index.js
src/ActionCreators/shelterActionCreators.js
src/Components/ShelterAdminPortal/ModalUpdate.js
src/Components/ShelterAdminPortal/ModalUpdateShelter.js
src/Components/ShelterAdminPortal/ShelterProfile.js
src/Reducers/SheltersReducer.js

These commits make it possible to update the shelter.

Shelter profile

---

src/Components/HostListView/HostListHeader.js
src/Components/HostListView/index.js

Made some basic style changes to the Host List View.  Created a basic Host List Header.

created host list header. made minor style changes

---

src/Components/PublicView/HeaderImageScroll.js

Clicking on an animal picture in the homepage image scroll will direct to the animals profile page.

Make animal pictures clickable on public page

---

src/ActionCreators/authActionCreator.js
src/Components/App.js
src/Components/FrontPageNav/index.js
src/Components/Nav/index.js
src/Components/index.js
src/Reducers/AuthReducer.js

This is a very basic provisional nav component.
Also, as a special bonus, I fixed a but in the logout -- it now correctly clears the localStorage.

Nav header

---

src/Components/AnimalProfileView/AnimalProfile.js

The functionality on this was for updating if the shelter was logged in they were the only ones that could see the host and if another user or guest was on the system then it wouldn't show the host at all.  I also added it in so that it displays the host name instead of the id and if there is no host I put an N/A on there.

79 update animal profile

---

src/Components/AnimalList/index.js
src/Components/AnimalListView/AnimalFilter.js
src/Components/AnimalListView/index.js

This is a provisional submission that demonstrates some basic filtering ability.  Additional filtering and styling is forthcoming.

Create animal filter

---

src/Components/Nav/index.js

Changes the login & logout buttons to be #77E8E8 color.

Modified Login & Logout buttons for Leah.

---

src/Components/FrontPageNav/index.js

Additional styling may still be necessary for the Register and the Donate sections.  I will finish the Adopt a Friend section (populating it with animal cards of all animals available for adoption) under another pull request.  Please let me know if you prefer something different re: styling.

first set up of updates to the Register and Donate sections of main page

---

src/Components/AnimalList/AnimalCard.js
src/Components/AnimalListView/AnimalFilter.js
src/Components/AnimalListView/index.js

The adoption status filter is only visible to the shelter admin

Add filters for animal age and adoption status

---

src/Components/FrontPageNav/index.js

Scroll bar at the top displays over the other items so you can click it.

Set scroll bar to be on top of everything else using zIndex

---

src/Components/ShelterAdminPortal/ModalAddAnimal.js

removed hostId from add animal. Submit button is now disabled until required fields are filled.

removed hostId from add animal.

---

src/Components/App.js
src/Components/FrontPageNav/index.js
src/Components/PublicView/HeaderImageScroll.js

height is auto on all sections of homepage. Changed styling of pictures in the header of the main page. Removed devnav.

minor style changes to main page

---

src/Components/AnimalProfileView/ModalUpdate.js

This removes the ability to change an animal's host, shelter, or animal id and corrects the code for updating its DOB

removed unneeded options, corrected DOB logic

---

src/Components/AnimalProfileView/AnimalProfile.js
src/Components/AnimalProfileView/index.js

I did some styling with this and some changes.  I wanted to push this and I am going to work on getting it to display the pregnancy portion only if it's a female . That will be another request.

Animal profile extra styling
